gmail_username: 'fablabzeeland@gmail.com'
gmail_password: 'Z33landf@bl@b'

development:
  google_client_id: 904396810966-406ggaro8mmtesq832rst6kb3otfhpbn.apps.googleusercontent.com
  google_client_secret: IDJykIf3Qa_ofkv3u7rJ-PGs